---
title: "SST-115 Introduction to Statistics (Fall 2025)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

$~$

Last updated: `r format(Sys.time(), "%a %b %e %Y, %H:%M")`

<hr style="border:3px solid black">
    




# Midterm
[Midterm Instructions](lectures/Description_of_the_Assignment.pdf)


| Step | Due Date | 
|:-----|:-------|
| Data Selection/Project Proposal| October 10|
| Data Reading/Check In| October 31|
| Presentations | November 14 |

<hr style="border:3px solid black">

# Homework
All homework is due at 9pm unless clearly specified otherwise. 

| Rmd | Due Date | Helpful Things | 
|:-----|:-------|:-----|
|[ Homework 1 ](homework/homework_1.Rmd)| October 1st |[ Examples of the graphs you'll be remaking ](homework/hw_1_example_graphs.pdf)|

<hr style="border:3px solid black">



<br>

# Required Readings
| Title | Author | Journal | Year | Quiz|
|:-----|:-------|:-----|:-----|:-----|
|Tidy Data| Hadley Wickham| Journal of Statistical Software|2014|9/15|
|Principles of Effective Data Visualization| Stephen R. Midway | Patterns | 2020 | 10/6|


Please note that you are fully allowed (encouraged even!) to visit during office hours to talk about the required reading if you'd like. I'm glad to chat about it and discuss any questions you might have. Also please note that I'd like you to understand the broad strokes of the paper/what the author is getting at. I will avoid quizzing you over the nitty-gritty details.




<hr style="border:3px solid black">



<br>

# Notes

<hr style="border:2px solid grey">
    


### Week 1 (Introduction)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Friday 8/28 | [Syllabus](syl_115_tester.html) | - | - |
|          | [Introduction](lectures/intro_115-2.pdf)  | - | IMS Sections 1.2.1-1.2.3 |

**Assignments and Deadlines**

1) Install R (https://cran.r-project.org/)

2) Install RStudio (https://posit.co/download/rstudio-desktop/)

3) Begin thinking of interesting data sources for you midterm projects

<hr style="border:2px solid grey">
    

<br>




### Week 2 (R)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Wednesday 9/3 | [Intro to R](lectures/r-2.pdf) |  [lab 1](labs/01_introR.html)|-  
| -|-| [lab 1 Helpful Hints](labs/Lab_1_hints.html)|-   
| Friday 9/5 | [Visualizations in R](lectures/data_vis_update.pdf)|  [Continue lab 1](labs/01_introR.html)|- | 

**Assignments and Deadlines**

1) First lab is due Septmber 9th
2) Hadley Wickham's Tidy Data published in Journal of Statistical Software in 2014 with a quiz on September 15th


<hr style="border:2px solid grey">
    

<br>




### Week 3 (Data Visualization)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Monday 9/8 | Finish Data Visualization  | |- 
| Wednesday 9/10 | [Data Visualization Part II](lectures/data_vis_2-4.pdf) |  lab 2 (to be posted later)|-  
| Friday 9/12 | [Data Visualization Part III Accessibility](lectures/accessible_graphics-2.pdf) | [data vis lab](labs/DataVisualizationLab.Rmd)-  



**Assignments and Deadlines**

1) First lab is due Septmber 9th
2) Hadley Wickham's Tidy Data published in Journal of Statistical Software in 2014 with a quiz on September 15th



<hr style="border:2px solid grey">
    

<br>


### Week 4 (ggplot2 and Numeric Summaries)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Monday 9/15 | [ggplot2](lectures/ggplot2-3.pdf)  | finish lab 2, [ggplot 2 lab](labs/ggplot2_lab.Rmd) |- 
| Wednesday 9/17 |  | [finish ggplot 2 lab](labs/ggplot2_lab.Rmd) |- 
| | | [ggplot2 lab helpful hints](labs/ggplot2_lab_help.html)| |
| Friday 9/19 |  [Numeric Summaries](lectures/numeric_summaries.pdf)  | If time work on ggplot2 lab |- 



**Assignments and Deadlines**

1) Second lab is due September 15th
2) ggplot2 lab is due September 24th

<hr style="border:2px solid grey">
    

<br>


### Week 5 (Numeric Summaries + Correlations)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Monday 9/22 |  [Numeric Summaries Cont.](lectures/numeric_summaries.pdf)  | |[NumericCode Along](R/Code_Along_115.Rmd) 
| Wednesday 9/24 |  [Correlations](lectures/correlation-2.pdf)  | |[Numeric Code along finished](lectures/Code_Along_115_completed.Rmd)
| Friday 9/26 |  [Finish Correlations](lectures/correlation-2.pdf)  | |[Correlation Code along](labs/cor_code_along_115.rmd)
| | |  | [Correlation Code along finished](labs/cor_code_along_115_finished.rmd)






**Assignments and Deadlines**

1) ggplot2 lab is due September 24nd
2) Homework 1 is due October 1st
3) Second required reading quize is October 6th


<hr style="border:2px solid grey">
    

<br>



### Week 6 (Linear Regression)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Monday 9/28 |[Simple Linear Regression (SLR)](lectures/slr_115_extended.pdf) |  | 
| Wednesday 10/01 |[Simple Linear Regression Cont.](lectures/slr_115_extended.pdf) |  | 
| Friday 10/03 | | [Cor., SLR, and R$^2$ Lab](labs/correlation_linear_regression_lab.rmd)  |



**Assignments and Deadlines**

2) Homework 1 is due October 1st
3) Second required reading quiz is October 6th







### Week 7 (Linear Regression Continued)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Monday 10/6 |[Regression: Transformations](lectures/transforms_updated.pdf) | | Slide 29 corrected |
| Wednesday 10/8 |[Trans. continued, indicators possible](lectures/regression_with_indicators.pdf) | | [code along (not done)](R/legos_code_along.rmd) |
|  Wednesday 10/8  |[Indicators Alternative Slide Deck](lectures/regression_with_indicators_alternative_deck.pdf) | | Same material, presented differently |



**Assignments and Deadlines**

1) Regression Lab is due October 10th
2) Exam is October 15th


<br>


<hr style="border:3px solid black">


<br>


# Syllabus

Welcome to the course website for SST 115, Introduction to Statistics. To begin, you can find the course syllabus linked below:

- [Click here](syl_115_tester.html) to view the course syllabus

You can locate course content by scrolling, or by using the outline in the upper left. Please note: material will not be posted until we've reached that point in the course.


<hr style="border:3px solid black">

# Coding 
My goal is to include the R code that I use to make different graphs, expamples, etc..., for the course. Most of it will be more advanced than what I will teach you or that you need but I want you to have access to examples if you'd like.

Please go [here](coding.html).

