---
title: "STA-209 Applied Statistics (Fall 2025)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

$~$

Last updated: `r format(Sys.time(), "%a %b %e %Y, %H:%M")`

<hr style="border:3px solid black">
    



# Midterm
[Midterm Instructions](lectures/Description_of_the_Assignment.pdf)


| Step | Due Date | 
|:-----|:-------|
| Data Selection/Project Proposal| October 10|
| Data Reading/Check In| October 31|
| Presentations | November 14 |


# Exam
It'll be the full 80 minutes. You may bring a notecard and a calculator. If you do not have a calculator you may leave your answer unsimplified. Eg predicted price = \$ e^2.19.

| Study Guide | Date | 
|:-----|:-------|
|[Exam 1 Study Guide](exam/Exam_1_Study_Guide_209.pdf)| Friday October 17th|



# Homework

All homework is due at 9pm unless clearly specified otherwise. 

| Rmd | Due Date | Helpful Things | 
|:-----|:-------|:-----|
|[ Homework 1 ](homework/homework_1.Rmd)| October 1st |[ Examples of the graphs you'll be remaking ](homework/hw_1_example_graphs.pdf)|
|[ Homework 2 ](labs/homework_2.rmd)| October 15th | CODE NEEDED RIGHT AFTER YOU READ IN: legos\$Year <- as.factor(legos\$Year) |
|[ Homework 2  SOLUTIONS](hw_2_sol_209.pdf)|||

<hr style="border:3px solid black">



<br>

# Required Readings
| Title | Author | Journal | Year | Quiz|
|:-----|:-------|:-----|:-----|:-----|
|Tidy Data| Hadley Wickham| Journal of Statistical Software|2014|9/15|
|Principles of Effective Data Visualization| Stephen R. Midway | Patterns | 2020 | 10/6|
|Somewhere Over the Rainbow: An Empirical Assessment of Quantitative Colormaps| Yang Liu & Jeffrey Heer | Conference on Human Factors in Computing Systems Proceedings | 2018 | 11/7 |

Please note that you are fully allowed (encouraged even!) to visit during office hours to talk about the required reading if you'd like. I'm glad to chat about it and discuss any questions you might have. Also please note that I'd like you to understand the broad strokes of the paper/what the author is getting at. I will avoid quizzing you over the nitty-gritty details.


<hr style="border:3px solid black">



<br>

# Notes

<hr style="border:2px solid grey">
    


### Module 1 (Introduction)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Fri 8/28 | [Syllabus](syl_209_tester.html) | - | - |
|          | [Introduction](lectures/intro_115-2.pdf)  | - |IMS Sections 1.2.1-1.2.3 |

**Assignments and Deadlines**

1) Install R (https://cran.r-project.org/)

2) Install RStudio (https://posit.co/download/rstudio-desktop/)

3) Begin thinking of interesting data sources for you midterm projects

<hr style="border:2px solid grey">

<br>
    
### Module 2 (R)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Wednesday 9/3 | [Intro to R](lectures/r-2.pdf) |  [lab 1](labs/01_introR.html)|-  
| -|-| [lab 1 Helpful Hints](labs/Lab_1_hints.html)| [H. Wickham discussing enviroments in R](https://adv-r.hadley.nz/environments.html)|
| Friday 9/5 | [Visualizations in R](lectures/data_vis_update.pdf)|  [Continue lab 1](labs/01_introR.html)|- | 

**Assignments and Deadlines**

1) First lab is due Septmber 9th
2) Hadley Wickham's Tidy Data published in Journal of Statistical Software in 2014 with a quiz on September 15th

<hr style="border:2px solid grey">

<br>

   
### Module 3 (Data Graphics)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Monday 9/8 | [Data Visualization II (Boxplots)](lectures/data_vis_2-2.pdf) |  |-  |
| Wednesday 9/10 | [Data Visualization III (Accessibility)](lectures/accessible_graphics-3.pdf) | [data vis lab](labs/DataVisualizationLab.Rmd) |- 
| Friday 9/12 | - | Finish lab 2  |-  |


**Assignments and Deadlines**

1) First lab is due Septmber 9th
2) Hadley Wickham's Tidy Data published in Journal of Statistical Software in 2014 with a quiz on September 15th




<hr style="border:2px solid grey">

<br>

### Module 4 (ggplot2 and Numeric Summaries)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Monday 9/15 | [ggplot2](lectures/ggplot2-3.pdf) | [ggplot2 lab](labs/ggplot2_lab.Rmd) | -  |
| Wednesday 9/17 | |Finish ggplot2 lab| -  |
| | | [ggplot2 helpful hints](labs/ggplot2_lab_help.html)
| Friday 9/19 | [Numeric Summaries](lectures/numeric_summaries.pdf) | | [Code Along](R/Code_Along.Rmd)
**Assignments and Deadlines**

1) Second lab is due September 16th
2) ggplot lab is due September 23nd


<hr style="border:2px solid grey">

<br>


### Module 5 (Numeric Summaries)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Monday 9/22 | [Correlation if time](lectures/correlation-2.pdf) | - | [Finished Code Along](R/Code_Along.Rmd) |
|Wednesday 9/24 | [Correlation](lectures/correlation-2.pdf) | - | [Correlation Code Along](R/code_along_correlation.rmd) |
|Friday 9/26 | [Simple Linear Regression Part 1](lectures/slr_209-3.pdf) | | [Finished correlation code along](R/code_along_correlation_finished.rmd)


<hr style="border:2px solid grey">

<br>


### Module 6 (Linear Regression)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Monday 9/29|Finish Simple Linear Regression||[Linear Regression Code Along](./slr.rmd)|
|Wednesday 10/01 | |[Linear Regression Lab](./labs/correlation_linear_regression_lab.rmd)| |
|Wednesday 10/01 | |Finish Lab| |


<hr style="border:2px solid grey">

<br>



### Module 7 (Linear Regression Topics)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Monday 10/06|[Transformations ](lectures/transforms_updated.pdf)||Slide 29 corrected|
|Wednesday 10/08|Transformations Finished, [Categorical Predictors ](lectures/regression_with_indicators_new.pdf)||[Lego code_along](R/legos_code_along.rmd)|
|Wednesday 10/08|||[Lego code_along_finished](R/legos_code_along_filled.rmd)|
|Friday 10/10|||[Lego Code Along for Transforms ](R/legos_code_along_transforms.rmd)|
|Friday 10/10|||[Lego Code Along for Transforms Done](legos_code_along_transforms_done.rmd)|
**Assignments and Deadlines**
**Assignments and Deadlines**

1) Exam Friday October 17
2) Homework 2 due October 15th




<hr style="border:2px solid grey">

<br>




### Module 8 (Simulations and Review)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Monday 10/13|[Simulations ](lectures/Randomization_test-2.pdf)|||
|Wednesday 10/15| Review Day| | | 
|Friday 10/17 | Exam |||

**Assignments and Deadlines**

1) Exam Friday October 17
2) Homework 2 due October 15th

<br>



<hr style="border:2px solid grey">

<br>




### Module 9 (Probability and Permutation Test)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Monday Oct 27 | [probability](lectures/probability_209.pdf)  ||
|Wednesday Oct 29 | [Permutation Test](lectures/Permutation_Test_209.pdf)  ||[How to write a csv file](write_a_csv.Rmd)|
|Halloween| [Normal Distribution](lectures/Normal.pdf) ||


<hr style="border:2px solid grey">

<br>

### Module 10 (Sampling Distributions and T tests)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Nov 3| [Sampling Distributions](lectures/Normality_Now_What_.pdf)|
|Nov 5| [Z-tests if time](graphics/z_tests_209.pdf) | [Dice Lab](graphics/permutation_lab-3.pdf)|

<br>

**Assignments and Deadlines**
1) Reading Quiz Friday Nov 7th
2) Dice rolling lab Due: TBD (check after wednesday's class)


<br>

<hr style="border:3px solid black">

<br>

# Syllabus

Welcome to the course website for SAT 209, Applied Statistics. To begin, you can find the course syllabus linked below:

- [Click here](syl_209_tester.html) to view the course syllabus

You can locate course content by scrolling, or by using the outline in the upper left. Please note: material will not be posted until we've reached that point in the course.

<hr style="border:3px solid black">



<br>

# Coding 
My goal is to include the R code that I use to make different graphs, expamples, etc..., for the course. Most of it will be more advanced than what I will teach you or that you need but I want you to have access to examples if you'd like.

Please go [here](coding.html).
