---
title: "STA-209-03 Applied Statistics (Spring 2025)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

$~$


<hr style="border:3px solid black">
    





# Midterm
[Midterm Instructions](../labs/Description_of_the_Assignment_spring.pdf)


[Helpful Hints on Getting Data Ready](../../midterm_help.Rmd)



| Step | Due Date | 
|:-----|:-------|
| Data Selection/Project Proposal| Feburary 16|
| Data Reading/Check In| March 2nd|
| Presentations | Mach 25th |

<br>

<hr style="border:3px solid black">

<br>


# Exams
| Unit | Date | Review | 
|:-----|:-------|:-----|
| 1 | Feb 27th | [Review Sheet](../exams/Exam_1_Study_Guide_209.pdf) | 






# Required Readings

| Title | Author | Journal | Year | Quiz Date|
|:-----|:-------|:-----|:-----|:-----|
|Tidy Data| Hadley Wickham| Journal of Statistical Software|2014|2/04|
|Somewhere Over the Rainbow: An Empirical Assessment of Quantitative Colormaps| Yang Liu & Jeffrey Heer | Conference on Human Factors in Computing Systems Proceedings | 2018 | 2/20 |

Please note that you are fully allowed (encouraged even!) to visit during office hours to talk about the required reading if you'd like. I'm glad to chat about it and discuss any questions you might have. Also please note that I'd like you to understand the broad strokes of the paper/what the author is getting at. I will avoid quizzing you over the nitty-gritty details.

<br>


<hr style="border:3px solid black">



<br>

# Notes

<hr style="border:2px solid grey">
    


### Week 1 (Introduction)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Wed 1/21 | [Syllabus](./syl_209_3.html) | [Start of Class R Stuff](../applied_5/r_prep.html) | - |
|          | [Introduction](../lectures/intro_spring.pdf)  | - |IMS Sections 1.2.1-1.2.3 |
|    Friday 1/23      | [Basics of R ](../lectures/r-3.pdf) | [Lab 1](../labs/01_introR.Rmd)| |



<br>

<hr style="border:2px solid grey">

<br>

### Week 2 (Visualizations)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Mon 1/26| [Data Visualization](../lectures/data_vis_spring.pdf) | | |
| Wednesday 1/28 | [ggplot2](../lectures/ggplot2-4.pdf) | [ggplot2 lab](../labs/ggplot2_lab.Rmd) | |
|| [critique 2](../lectures/data_critique_2-2.pdf) | | |
|| [accessibility in graphics](../lectures/accessible_graphics-7.pdf)
| Friday 1/30 | [Numeric Summaries](../lectures/numeric_summaries_spring_class.pdf) |See Canvas for Video|


<br>

<hr style="border:2px solid grey">

<br>

### Week 3 (Numeric Summaries and Linear Regression)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Monday 2/2 | [Correlation](../lectures/correlation-2.pdf) | | 
| Wednesday 2/4 | [Simple Linear Regression](../lectures/slr_spring.pdf) | | 
| Friday 2/6 | Finish Simple Linear Regression |  [SLR Lab](../labs/correlation_linear_regression_lab.rmd) | 
  | | | | [Code Along Finished for Correlation](../../R/code_along_correlation_finished.rmd)   |
| | | | [Code Along Finished for Simple Linear Regression](../../slr.rmd)   |
<br>

<hr style="border:2px solid grey">

<br>



### Week 4 (Linear Regression: Topics)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Monday 2/2 | [SLR: Transformations](../lectures/transforms_spring.pdf) | | 
|Wednesday 2/4|||[Lego Code Along for Transforms ](../../R/legos_code_along_transforms.rmd)|
|Friday 2/6| [Regression with Indicators if time ](../lectures/regression_with_indicators_spring.pdf)| | [Lego Code Along for Transforms Finished](../../R/legos_code_along_transforms_finished.rmd)|

<br>

<hr style="border:2px solid grey">

<br>



### Week 5 (Linear Regression: Topics 2)
| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Monday 2/16| [Regression with Indicators ](../lectures/regression_with_indicators_spring.pdf)| [Linear Regression Exploration](../../labs/lego_land_lab.rmd) | |
|Wednesday 2/18| Practice worksheet and continue lab|||
|Friday 2/20 | [Multiple Regression](../lectures/mulitple_regression_spring.pdf)
<br> 


<br>

<hr style="border:2px solid grey">

<br>




### Week 6 (Exam and Unit 2)
| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Monday Feb 23| Review and Practice | ||
|Wednesday Feb  25 | [probability](../../lectures/probability_209.pdf)  ||

<hr style="border:3px solid black">



<br>

# Syllabus

Welcome to the course website for SAT 209, Applied Statistics. To begin, you can find the course syllabus linked below:

- [Click here](./syl_209_3.html) to view the course syllabus

You can locate course content by scrolling, or by using the outline in the upper left. Please note: material will not be posted until we've reached that point in the course.

<hr style="border:3px solid black">


