---
title: "Math 104 Elementary Statistics @ 1:40am (Fall 2026)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

$~$

<hr style="border:3px solid black">




# Required Readings
| Title | Author | Journal | Year | Quiz|
|:-----|:-------|:-----|:-----|:-----|
|Somewhere Over the Rainbow: An Empirical Assessment of Quantitative Colormaps| Yang Liu & Jeffrey Heer | Conference on Human Factors in Computing Systems Proceedings | 2018 | 09/01 |
|Science and Statistics | George Box | Journal of the American Statistical Association | 1976 | 

<hr style="border:3px solid black">


  
<br>


# Midterm
[Midterm Instructions](../exam/midterm_tuesday.pdf)

| Step | Due Date | 
|:-----|:-------|
| Data Selection/Project Proposal| October 6th|
| Data Check In| October 20th |
| Presentations | November 5th |



# Exam
It'll be the full 80 minutes. You may bring a notecard and a calculator. If you do not have a calculator you may leave your answer unsimplified. Eg predicted price = \$ e^2.19.

| Exam | Study Guide | Date | 
|:-----|:-------|:-----|
Exam 1 | [Study Guide](../notes/exam_1_study_guide_104.pdf) | Sept 22nd |

<hr style="border:3px solid black">

<br>

# Syllabus

Welcome to the course website for Math 104! To begin, you can find the course syllabus linked below:

- [Click here](syl.html) to view the course syllabus

You can locate course content by scrolling, or by using the outline in the upper left. Please note: material will not be posted until we've reached that point in the course.

<hr style="border:3px solid black">


  
<br>

# Schedule




<br>


### Week 1

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Aug 18| [Basics of Statistics + 5 number summary](../notes/Boxplot_overviews.pdf)||
|Aug 20| 5 Num. Summary, Boxplots, and Histograms |||


### Week 2

| Date | Lecture | HW Due | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Aug 25| [Histograms and Numeric Summaries](../notes/numeric_summaries_cofc.pdf)| HW 1 due 08/28 at 4:00pm at my office door (a drop off box/folder will be made for it) |  [HW 1 solutions](../notes/hw_boxplots_sol-2.pdf) |
|Aug 27| [Scatterplots and Correlation](../notes/correlation.pdf)| [Histogram Practice Worksheet](../../Rplots.pdf)|[Histogram Practice Solutons](../notes/histograms_worksheet_ans.pdf)|


### Week 3

| Date | Lecture | HW Due | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Sept 1| [Finish Correlation and then bar plots](../notes/bar_lplots.pdf)| HW 2 due 09/05 at 4:00pm at my office door (a drop off box/folder will be made for it) | [HW 2 Solutionw](../notes/homework_lego_nummeric_summaries_sol.pdf)|
|Sept 3| [Finish Correlations and bar plots](../notes/bar_lplots.pdf) |
|      | [If time, probability](../notes/probability_209.pdf)|


### Week 4

| Date | Lecture | HW Due | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Sept 8| Finish Probability | HW due 4pm on Friday Sept 11|  [HW 3 Solutions](../notes/homework_prob-2.pdf)  |
|Sept 10 | Probability | 


### Week 5
| Date | Lecture | HW Due | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Sept 15| [Normality](../notes/Probability_two-2.pdf) ||
|Sept 17| Finish Normality and Review ||


### Week 6
| Date | Lecture | HW Due | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Sept 22| Exam and Intro to Midterm Project | ||