---
title: "Math 104 Elementary Statistics @ 11am (Fall 2026)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

$~$

<hr style="border:3px solid black">

# Required Readings
| Title | Author | Journal | Year | Quiz|
|:-----|:-------|:-----|:-----|:-----|
|Somewhere Over the Rainbow: An Empirical Assessment of Quantitative Colormaps| Yang Liu & Jeffrey Heer | Conference on Human Factors in Computing Systems Proceedings | 2018 | 08/31 |
| Science and Statistics | George Box | Journal of the American Statistical Association | 1976 | 04/06 | [Box quiz solutions](../exams/box_quiz_w_sol.pdf)|

<hr style="border:3px solid black">

  
<br>


# Exam
It'll be the full 80 minutes. You may bring a notecard and a calculator. If you do not have a calculator you may leave your answer unsimplified. Eg predicted price = \$ e^2.19.

| Exam | Study Guide | Date | 
|:-----|:-------|:-----|
Exam 1 | [Study Guide](../notes/exam_1_study_guide_104.pdf) | Sept 18th |

<hr style="border:3px solid black">

<br>

# Syllabus

Welcome to the course website for Math 104! To begin, you can find the course syllabus linked below:

- [Click here](syl.html) to view the course syllabus

You can locate course content by scrolling, or by using the outline in the upper left. Please note: material will not be posted until we've reached that point in the course.
  
<br>

<hr style="border:3px solid black">


  
<br>

# Schedule





    

### Week 1 (Introduction)

| Date | Lecture | Lab | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Aug 17| [Basics of Statistics + 5 number summary](../notes/Boxplot_overviews.pdf)||
|Aug 19| 5 Num. Summary + Boxplots|||
|Aug 21 | Boxplots and Histograms ||


### Week 2 (Histograms and Numeric Summaries)

| Date | Lecture | HW Due | Other |
|:-----|:-------|:-----|:-----|
|Aug 24| [Histograms and Numeric Summaries](../notes/numeric_summaries_cofc.pdf)|  HW 1 due 08/28 at 4:00pm at my office door (a drop off box/folder will be made for it) | [HW 1 solutions](../notes/hw_boxplots_sol-2.pdf) |
|Aug 26| [Scatterplots and Correlation](../notes/correlation.pdf)| [Histogram Practice Worksheet](../../Rplots.pdf)|[Histogram Practice Solutons](../notes/histograms_worksheet_ans.pdf)|
|Aug 28| [Scatterplots and Correlation](../notes/correlation.pdf)| [Histogram, Boxplot, Scatterplot Practice Worksheet](../../new_wkst.pdf)|[Solutions](../notes/hist_extra_sol.pdf)|



### Week 3 (Correlations and Barplots)

| Date | Lecture | HW Due | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Aug 31| Quiz Day and Correlations | HW 2 due at 4pm on Sept 4 at my office (RSS 333) |[HW 2 Solutionw](../notes/homework_lego_nummeric_summaries_sol.pdf)
|Sept 2| [Barplots](../notes/bar_lplots.pdf) |
|Sept 4| [Probability](../notes/probability_209.pdf) |


### Week 4 (Probability and Normal)

| Date | Lecture | HW Due | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Sept 7| Finish Probability | HW due 4pm on Friday Sept 11|  [HW 3 Solutions](../notes/homework_prob-2.pdf)  |
|Sept 9| Probability Continued + Dice Activity| |
|Sept 11| [Normality if time](../notes/Probability_two-2.pdf)|[Probability Practice](../notes/probability_practice.pdf)|[Practice Solutions](../notes/probability_practice_sol.pdf)



<hr style="border:2px solid grey">

<br>

### Week 5 (Normality and Exam)
| Date | Lecture | HW Due | Suggested Reading |
|:-----|:-------|:-----|:-----|
| Sept 14th | Normality Continued | NA ||
|Sept 16th | Review for Exam ||
|Sept 18th | Exam ||


<hr style="border:2px solid grey">

<br>

### Week 6 (Sampling Distributions)
| Date | Lecture | HW Due | Useful Stuff |
|:-----|:-------|:-----|:-----|
|Sept 21st | Practice Normal and Prep for [Sampling Dists](../notes/Normality_Now_What_.pdf)| HW 4 due Friday Sept. 25th.| [link to Normal Dist. Calculator](https://www.statdistributions.com/normal/)| 


