---
title: "Math 104 Elementary Statistics @ 9am (Fall 2026)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

$~$

# Required Readings
| Title | Author | Journal | Year | Quiz|
|:-----|:-------|:-----|:-----|:-----|
|Somewhere Over the Rainbow: An Empirical Assessment of Quantitative Colormaps| Yang Liu & Jeffrey Heer | Conference on Human Factors in Computing Systems Proceedings | 2018 | 08/31 |

<hr style="border:3px solid black">


 

  
<br>


# Syllabus
  
  Welcome to the course website for Math 104! To begin, you can find the course syllabus linked below:
  
  - [Click here](syl.html) to view the course syllabus

You can locate course content by scrolling, or by using the outline in the upper left. Please note: material will not be posted until we've reached that point in the course.

<hr style="border:3px solid black">


 

  
<br>

# Schedule






    

### Week 1

| Date | Lecture | HW Due | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Aug 17| [Basics of Statistics + 5 number summary](../notes/Boxplot_overviews.pdf)||
|Aug 19| Continuing ||
|Aug 21| Continuing ||



### Week 2

| Date | Lecture | HW Due | Suggested Reading |
|:-----|:-------|:-----|:-----|
|Aug 24| [Histograms and Numeric Summaries](../notes/numeric_summaries_cofc.pdf)| HW 1 due 09/28|


