---
title: "Elementary Statistics Sylabus"
author: "Vinny Paris"
date: "2026-08-20"
output:
  pdf_document: default
  html_document: default
---

# Syllabus \- Math-104 (Fall 2026\)

**Instructor**:

* Vinny Paris
* 333 Small Hall
* parisvv at cof...

**Class Meetings**:

* Math 104  Section 08
* 113 Maybank
* MWF 9am

**Office Hours**:

* Location: Small 333 (Vinny's Office)
* Monday 3:10-4:30pm,
* Tuesday 3:10-4:30pm
* Open door -> Feel free to pop your head in
* If these times do not work for you, *please* message me and we will find a time to meet.


**Prerequists**

Placement or any 100 level math course
<hr style="border:2px solid grey">

**Course Description**:

This course covers the application of basic statistical methods such as univariate graphics and summary statistics, basic statistical inference for one and two samples, and categorical data analysis. (You will learn all these terms throughout the semester\!)


<hr style="border:2px solid grey">

**Texts**:

* [Introduction to Modern Statistics, 1st Edition](https://openintro-ims.netlify.app/) (Free online\!)
* Beginning Statistics by Hawkes, published by Wiley. 

All additional materials will be posted on the course website.

There will be required readings from other sources which will be provided as necessary. Mostly these will be short papers.

<br>

<hr style="border:3px solid black">


## Aims and Objectives

This course aims to introduce students to the field of statistics, including its vocabulary and fundamental principles. The course will prepare students to read, recognize, interpret, and discuss statistical concepts and their use in scientific applications. The course will provide students an understanding of the role of statistics within the scientific method, and provide students the tools to use data to make informed conclusions. The mathematical foundations for these will be covered in detail.

#### Learning Objectives

After completing this course, students should be able to:

* Apply methods of exploration, visualization, and statistical analysis to data in order to illustrate key findings and make justifiable inferences
* Communicate the methods and results of statistical analyses succinctly and accurately in both writing and speaking  
* Read, identify, and critique the statistical concepts and choices of data presentation used in various media publications (newspaper articles, reports, blogs, etc.)

<br>

<hr style="border:3px solid black">


<br>

## Grading




**Individual Homework** \- 20%

Homework will be assigned regularly. You may turn in your exactly two late homeworks or labs and recieve 80% credit. All other late homework will not be graded (although it will still be commented on). Your lowest two scores will be dropped (which can include 0's). Homework will be due on Canvas, generally due 9pm on Tuesdays. 

I encourage you to work with other students or visit the Math Lab for help on homework questions, but you should clearly understand all your answers and your assignment should be entirely in your own words. The homework is intended primarily as an exercise to practice and develop your understanding and to assist in identifying weaknesses: you do yourself a disservice if you submit work that you do not fully understand. I try to not assign "busy work".

If you engage in significant collaboration with classmates or tutors, you must explicitly acknowledge that person(s) on the top of your assignment (again, you are encouraged to collaborate, and I want to emphasize that there is no penalty for doing so). For example, Jack and Jill working together and producing similar answers (right or wrong) is fine. Jack turning in verbatim Jill's answers is not okay. Jack turning in code that is exactly the same as Jill's is also not okay. 

<hr style="border:2px solid grey">

**Required Readings** \- 20%

At least three papers will be assigned during the course of the semester to read. They will not be overly long nor mathematically difficult to read. The goal of these papers is to help solidify the big picture understanding that I want you to walk out of here with. A single paper will be assigned one to two weeks before a small quiz on it will be done in class. These quizzes will be closed notes/papers.

These papers will be distinct from the suggested reading tab in the module summary.


<hr style="border:2px solid grey">


**Exams (3)** \- 20% each

There will be 2 midterms and a final exam. Each midterm will focus on a specific set of content, but because course topics are naturally cumulative there may be some questions involving earlier content. The 3 exams will contribute a total 60% towards your end-of-semester grade. Your lowest exam grade will be replaced by it's percentage's square root mulitplied by ten (eg if your lowest test score is 64% it will become 10\*sqrt(64) = 80%).

Exams will be announced at least a week and a half in advance. Exams will be closed notes, but you will be permitted to bring a note card (3in x 5in, both sides can be written on) and a calculator (no cellphone use allowed). 

Alternative exam arrangements need to be made at least one week in advance of the time you plan to take the exam; this includes taking the exam in a different location, or times going beyond the given class time. Alternative arrangements are not guaranteed unless proper notification is given. There will be sufficent time after the announcement of an exam to seek an accomodation.

For those of you with accommodations, those accommodations are your right and I intend to respect those rights fully. Even if the semester has already started and you want/need an accomodation we (the college) can do that for you. Please just reach out. Also note that I am never given your diagnosis/background for why; I'm just informed there is an accommodation which I will meet.

<hr style="border:2px solid grey">


<hr style="border:3px solid black">

## Policies


**Extensions for Assignments** 

Twice, and only twice, a semester you may submit either a homework late for 80% credit. The late assignmentmust be handed in before the exam over that material. Homework is not meant to be busy work but to give you practice with the material.

Please note that the deadline is the deadline and will be treated as a bright line cut off. Fairness is something that is very important to me and the only way I can find to be absolutely fair and not show favoritism is by making a bright line rule. The due date and time is the due date and time. If you are late you may use one of your two late submissions. Beyond that I will not give credit for late work.


<hr style="border:2px solid grey">



**Attendance**

Because this course involves some amount of group work, absences impact not only yourself but also your classmates. That said, I understand that missing class is sometimes necessary. I will not take attendance directly, but labs occasionally being missed will affect lab scores. There is leeway built into these (see Participation and Labs above). 

Please note that if you are sick I do NOT want you in class. Please do not come to class. If you show up and are clearly demostrating sympotoms of being sick you will be asked to leave. 

<hr style="border:2px solid grey">

**Software**

Software is increasingly an essential component of statistics and will play a role in this course. As the semester goes on which particular software we use, if any, will be discussed. All things needed will be shown in class or instructions given in assignments.


<hr style="border:2px solid grey">

**Academic Honesty**

At the College of Charleston you are part of a conversation among scholars, professors, and students, one that helps sustain both the intellectual community here and the larger world of thinkers, researchers, and writers. The tests you take, the research you do, the writing you submit-all these are ways you participate in this conversation.

The College presumes that your work for any course is your own contribution to that scholarly conversation, and it expects you to take responsibility for that contribution. That is, you should strive to present ideas and data fairly and accurately, indicate what is your own work, and acknowledge what you have derived from others. This care permits other members of the community to trace the evolution of ideas and check claims for accuracy.

Failure to live up to this expectation constitutes academic dishonesty. Academic dishonesty is misrepresenting someone else’s intellectual effort as your own. Within the context of a course, it also can include misrepresenting your own work as produced for that class when in fact it was produced for some other purpose. 

<hr style="border:2px solid grey">

**Inclusive Classroom**

The College of Charleston makes reasonable accommodations for students with documented disabilities. To receive accommodations, students must provide documentation to the college. If you plan on using accommodations in this course, you should speak with me as early as possible in the semester so that we can discuss ways to ensure your full participation in the course.

<hr style="border:2px solid grey">

**Religious Holidays**

I encourage students who plan to observe holy days that coincide with class meetings or assignment due dates to consult with me in the first three weeks of classes so that we may reach a mutual understanding of how you can meet your religious observance, and the requirements of the course.

<hr style="border:2px solid grey">


**Large Language Models**

Large language models, such as ChatGPT, Bing Chat, or Bard, can be a useful tool for explaining and fixing errors or helping you understand examples. I myself am optimistic about LLM's abilities to cut down on ''data cleaning'' and am looking forward to folding that into future statistical consulting work I might do. You are welcome to use these tools; however, you are ultimately responsible for the accuracy of any code or written work you submit. Relying upon a large language model to write for you is a risky endeavor. The model may provide inaccurate information or generate text that is superficial and lacking sufficient detail. I encourage you to read Professor Erik Simpson’s write-up on writing with LLMs to see some reasons why you shouldn’t lean too heavily on these technologies. Nevertheless, you’re welcome to use large language models in this course in the same way you’d use a website like Stack Overflow or a peer mentor. Overly relying on these tools may set you up to do poorly on exams. 

To be abundantly clear, simply copying and pasting the output from a LLM is not acceptable work for this course. 

*Note: My stance on LLM usage through the course may change, but you will be given notice and, if applied retroactively, won't lower your grade*


<hr style="border:3px solid black">

### Sketch of Schedule
